title: Veri Topluluğu AI Agent
description: >-
  A course on prompt engineering, building AI agents from scratch with Claude,
  and an introduction to AI-native teams.
theme: jekyll-theme-cayman
show_downloads: false

markdown: kramdown
